### ISSUE TITLE
Use Standard Logical Connectives Instead of Custom Symbols

### ISSUE THREAD

**Issue by DanielYang59** [abravalheri/experiment-setuptools-package-data#1]
Re-post from https://github.com/pypa/setuptools/issues/4638#issuecomment-2354434831 to it tracked:

> as "include or not" is a binary logic, can we use the standard [logical connectives](https://en.wikipedia.org/wiki/Logical_connective) instead of creating definition ourselves? It was a bit hard to read, and defining + as OR is a bit counter-intuitive to me (I would read + as AND in my brain 😄 ).

**Comment by abravalheri** [comment]
Please note that the current document *does already use a* standard notation used in Boolean algebra and logic circuits . For example, you can see similar if not the same notation being used in [wikipedia](https://en.wikipedia.org/wiki/Karnaugh_map#2-variable_map_examples):
![image](https://github.com/user-attachments/assets/4850e70f-c6e6-4bc5-8bdb-c9bbe4d4abb9) or in [educational](http://web.cs.ucla.edu/~yutao/w05-csm51a/Lec6_0131.ppt) [material in universities](https://web.cs.ucla.edu/Logic_Design/SLPDF/ch5.pdf):
![image](https://github.com/user-attachments/assets/bdcb0159-9c2e-42e3-80b1-9e03165e51a3) 
![image](https://github.com/user-attachments/assets/b036d0d5-6100-4be9-90c6-211b93327c6e) (probably grad/post-grad books too, but I don't remember which ones I used when I was at uni :P).



The notation is particularly useful in this context because the README describes the procedure used to obtain these expressions (Karnaugh maps and the Quine-McCluskey algorithm), which are presented in books that usually rely on similar notation.

(So by no means this repo is employing custom symbols).

**Comment by DanielYang59** [comment]
Ah thanks a lot for the comment again, I was afraid there might some background that I was missing, which indeed looks like is the case :)
